### ISSUE TITLE
Infernal potion effects last well over a playable, reasonable amount

### ISSUE THREAD

**Issue by Osseus-Corvum** [velvet-moe/InfernalMobs#14]
Put in a limit on potion effects like blindness, darkness, weakness, etc. that are 10 seconds at most, more generally likely 5 seconds for blindness and darkness, weakness for 10-20. I _highly_ recommend removing bad omen, anyone with a trading hall will know the pain of accidentally triggering a raid if they go within 30 feet of it.

Blindness - 5s
Darkness - 5s
Wither - 10s
Poison - 10s
Bad Omen - remove
Mining Fatigue - 10s at most
Levitation - 5s (10s brings people so close to death that it could legit just kill them)

**Comment by sargon64** [comment]
fixed with #2
