### ISSUE TITLE
Charms functionality issues

### ISSUE THREAD

**Issue by Osseus-Corvum** [velvet-moe/InfernalMobs#15]
A list of nonfunctional charms/ abnormal charm behavior

**Comment by Osseus-Corvum** [comment]
Glow Leaf does not provide glowing

**Comment by Osseus-Corvum** [comment]
Wardens Touch does not inflict darkness (2s per hit, annoying but able to be played with)

**Comment by Osseus-Corvum** [comment]
Totem of Death does not give mining fatigue

**Comment by Osseus-Corvum** [comment]
**Charm Weight Reworking**
Mothers Milk, Hunger Charm, Wardens Touch, Power Shard - Weight 1
All other items at weight 5 seem to be dropping fairly commonly which is not intended, suggest dropping them to weight 3 if its just them being too common at weight 5 and not another issue with drops

**Comment by ChecksumDev** [comment]
Glow leaf was mislabeled as a consumable, when it is a charm. This has been fixed in the main server.

**Comment by Osseus-Corvum** [comment]
'Pickel' of power does not give weakness

**Comment by Osseus-Corvum** [comment]
Golden Coins do not give luck

**Comment by Osseus-Corvum** [comment]
Angel feather does not give slow falling

**Comment by Osseus-Corvum** [comment]
Fire crystal does not give fire resistance

**Comment by Osseus-Corvum** [comment]
**Totem of Life/Death Rework**
As it stands, these items are pretty useless. I suggest that we make them both charms, with Death giving a revenge effect of Slowness I, and with Life giving Regeneration I. The function of them means they are usable to prevent death, but still provide an advantage. 

These would be a 3 weight drop.

**Comment by Osseus-Corvum** [comment]
Honey of the Eater only gives Slowness I, and provides a huge buff with Strength IV. Could we up the Slowness to 3, so it makes users sacrifice speed while gaining an immense amount of strength?

**Comment by Osseus-Corvum** [comment]
In the loot file the wardens touch is still 30 with 5 duration, thats not a great thing to have as a baseline for the plugin

**Comment by ChecksumDev** [comment]
I have created a branch to start doing some of these issues plugin-side, depending on the issue either me or @sargon64 will be making the commits.
